plugin: aws_ec2
regions:
  - "us-east-1"
keyed_groups:
  - key: tags.Name
  - prefix: instance_type
    key: instance_type
  - prefix: env
    key: tags['Environment']
compose:
  ansible_host: public_ip_address
groups:
  redhat: "'RedHat' in tags.OS"
  amznlnx2: "'AmazonLinux2' in tags.OS"
 

