{{- if ne .Values.createsecret false}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.resourcename}}-helm
  labels:
    {{- include "secret.defaultlabels" . | nindent 4}}
type: Opaque
data:
  secret.value.id: {{ required "please specify the value of secret.value" .Values.secret.creds.secretid | b64enc | quote}}
  secret.valuetwo.id: {{ required "please specify the secret.valuetwo.id" .Values.secret.creds.secretidtwo | b64enc | quote }}

  {{- if ne .Values.secretflag "create"}}
  k8s.secret.id: {{ .Values.secret.creds.secretid | b64enc | quote}}
  k8s.secret.cred: {{ .Values.secret.creds.secretidtwo | b64enc | quote }}
  {{- end}}
{{- end}}